version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "develop"
  schedule:
    interval: "weekly"

- package-ecosystem: "gomod"
  target-branch: "develop"
  schedule:
    interval: "weekly"
  directories:
  - "/"
  - "/assets/catnip"
  - "/assets/credhub-service-broker"
  - "/assets/go_calls_ruby"
  - "/assets/golang"
  - "/assets/grpc"
  - "/assets/http2"
  - "/assets/logging-route-service"
  - "/assets/pora"
  - "/assets/proxy"
  - "/assets/syslog-drain-listener"
  - "/assets/tcp-listener"
  - "/assets/worker"

- package-ecosystem: "docker"
  directory: "/assets/pora"
  target-branch: "develop"
  schedule:
    interval: "weekly"

- package-ecosystem: "bundler"
  vendor: true
  target-branch: "develop"
  schedule:
    interval: "weekly"
  directories:
  - "/assets/dora"
  - "/assets/go_calls_ruby"
  - "/assets/hello-routing"
  - "/assets/hello-world"
  - "/assets/loggregator-load-generator"
  - "/assets/ruby_simple"
  - "/assets/service_broker"

- package-ecosystem: "maven"
  directory: "/assets/java-spring"
  target-branch: "develop"
  schedule:
    interval: "weekly"

- package-ecosystem: "gradle"
  directory: "/assets/credhub-enabled-app"
  target-branch: "develop"
  schedule:
    interval: "weekly"
